# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
git:
  depth: 150

matrix:
  include:
    - os: linux
      dist: trusty
      r: devel

    - os: linux
      dist: trusty
      r: release

    - os: linux
      r: oldrel

    - os: osx
      osx_image: xcode8.1
      r: release

    - os: osx
      r: release

  allow_failures:
    - os: linux
      dist: trusty
      r: devel

r_packages:
  - covr

#after_success:
#  - Rscript -e 'library(covr); codecov()'
